#!usr/bin/fish

set NAME "tutorial" 
set DIR /home/m/Desktop/tutorial
set SOCKFILE /home/m/Desktop/tutorial/run/gunicorn.sock
set USER m
set GROUP m
set NUM_WORKERS 3
set DJANGO_SETTINGS_MODULE tutorial.settings
set DJANGO_WSGI_MODULE tutorial.wsgi
set LOG_LEVEL error

set -x DJANGO_SETTINGS_MODULE $DJANGO_SETTINGS_MODULE
set -x PYTHONPATH $DIR:$PYTHONPATH

exec /home/m/.local/share/virtualenvs/tutorial-rVvgsrqZ/bin/gunicorn $DJANGO_WSGI_MODULE --workers $NUM_WORKERS --bind unix:$SOCKFILE --name $NAME --user $USER


