# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_blogpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
