# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170918_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_body',
        ),
    ]
