# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_comment_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_name',
            new_name='Name',
        ),
    ]
