# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170918_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_blogpost',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date',
            new_name='date',
        ),
    ]
