# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170919_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='Namec',
        ),
    ]
