# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170919_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Namec',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
