# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wonder', to='home.BlogPost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.CharField(max_length=500),
        ),
    ]
