# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170919_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='home.BlogPost'),
        ),
    ]
