# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20170919_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BlogPost'),
        ),
    ]
