# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_blogpost_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pub_date',
        ),
    ]
