# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='pic',
        ),
    ]
