# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-31 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_blogpost_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
